services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    volumes:
      - wordpress_vol:/var/www/html/
    restart: always
    networks:
      - app-net
    env_file:
      - .env
    ports:
      - "1222:443"

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database_vol:/var/lib/mysql
    networks:
      - app-net
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    volumes:
      - wordpress_vol:/var/www/html/
    restart: always
    networks:
      - app-net
    env_file:
      - .env

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      device: /home/$USER/data/wordpress
      o: bind
      type: none
  database_vol:
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none

networks:
  app-net:
    driver: bridge
